version: "3.8"

services:
  server:
    image: node:current-alpine
    env_file:
      - .env
    command:
      sh -c "npm install -g @nestjs/cli && npm install && npm run start:dev"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./server:/app

  client:
    image: node:lts-alpine
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./client:/app

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-dev-quicksend:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080
    logging:
      driver: none

  admin:
    image: node:current-alpine
    command:
      sh -c "cd admin/ && npm install -g typeorm &&  npm install && /bin/ash"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./admin:/app/admin
      - ./server:/app/server
      - ./client:/app/client
    tty: true

volumes:
  postgres-dev-quicksend:
