version: "3.8"

services:
  server:
    build: ./server
    env_file:
      - .env
    ports:
      - 5000:5000

  client:
    build: ./client
    env_file:
      - .env
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-quicksend:/var/lib/postgresql/data

volumes:
  postgres-quicksend:
