version: "3.8"

services:
  server:
    build: ./server
    env_file:
      - .env
    ports:
      - 5000:5000
    restart: always

  client:
    build: ./client
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-quicksend:/var/lib/postgresql/data
    restart: always

  admin:
    image: node:current-alpine
    command:
      sh -c "npm install -g typescript && npm install -g ts-node && npm install
      @types/node --save-dev && npm install -g typeorm && cd admin/ && /bin/ash"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./admin:/app/admin
      - ./server:/app/server
      - ./client:/app/client
    tty: true
    restart: always

volumes:
  postgres-quicksend:
